### ISSUE TITLE
Compiling bug : no member named parent

### ISSUE THREAD

**Issue by nicotep** [zrna-research/akso-factory#5]
When loading jt's example "grainy-table", I get this...

Compiling patch.
/Users/nicotep/Library/Akso/build/xpatch.cpp: In member function 'void rootc::instancepatcher__1::voice::instanceplay__1::dsp(rootc::instancepatcher__1::voice*, bool, bool, int32_t, int32_t, int32_t (&)[16], int)':
/Users/nicotep/Library/Akso/build/xpatch.cpp:941:43: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
       pos = ((uint64_t)(asat>>(27-parent->parent->instancet1_i.LENGTHPOW)))<<32;
                                           ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:954:29: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
       if ((pos>>32)<parent->parent->instancet1_i.LENGTH) {
                             ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:955:40: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          uint32_t r = ___SMMUL(parent->parent->instancet1_i.array[pos>>32]<<parent->parent->instancet1_i.GAIN,INT32_MAX-(((uint32_t)pos)>>1));
                                        ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:955:85: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          uint32_t r = ___SMMUL(parent->parent->instancet1_i.array[pos>>32]<<parent->parent->instancet1_i.GAIN,INT32_MAX-(((uint32_t)pos)>>1));
                                                                                     ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:956:31: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          r = ___SMMLA(parent->parent->instancet1_i.array[(pos>>32)+1]<<parent->parent->instancet1_i.GAIN,(((uint32_t)pos)>>1),r);
                               ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:956:80: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          r = ___SMMLA(parent->parent->instancet1_i.array[(pos>>32)+1]<<parent->parent->instancet1_i.GAIN,(((uint32_t)pos)>>1),r);
                                                                                ^~~~~~
make: *** [/Users/nicotep/Library/Akso/build/xpatch.o] Error 1
Compiling patch failed.
shell task failed, exit value: 2
axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.ShellTask.run(ShellTask.java:120)
	at axoloti.shell.ShellTask.lambda$getJob$0(ShellTask.java:37)
	at axoloti.shell.CompilePatch.lambda$run$0(CompilePatch.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)

axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.CompilePatch.run(CompilePatch.java:75)
	at axoloti.live.patch.PatchViewLive.lambda$goLive$7(PatchViewLive.java:275)
	at axoloti.job.JobProcessor.lambda$exec$0(JobProcessor.java:21)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Generate code complete
Compiling patch.
/Users/nicotep/Library/Akso/build/xpatch.cpp: In member function 'void rootc::instancepatcher__1::voice::instanceplay__1::dsp(rootc::instancepatcher__1::voice*, bool, bool, int32_t, int32_t, int32_t (&)[16], int)':
/Users/nicotep/Library/Akso/build/xpatch.cpp:941:43: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
       pos = ((uint64_t)(asat>>(27-parent->parent->instancet1_i.LENGTHPOW)))<<32;
                                           ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:954:29: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
       if ((pos>>32)<parent->parent->instancet1_i.LENGTH) {
                             ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:955:40: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          uint32_t r = ___SMMUL(parent->parent->instancet1_i.array[pos>>32]<<parent->parent->instancet1_i.GAIN,INT32_MAX-(((uint32_t)pos)>>1));
                                        ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:955:85: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          uint32_t r = ___SMMUL(parent->parent->instancet1_i.array[pos>>32]<<parent->parent->instancet1_i.GAIN,INT32_MAX-(((uint32_t)pos)>>1));
                                                                                     ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:956:31: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          r = ___SMMLA(parent->parent->instancet1_i.array[(pos>>32)+1]<<parent->parent->instancet1_i.GAIN,(((uint32_t)pos)>>1),r);
                               ^~~~~~
/Users/nicotep/Library/Akso/build/xpatch.cpp:956:80: error: 'class rootc::instancepatcher__1::voice' has no member named 'parent'
          r = ___SMMLA(parent->parent->instancet1_i.array[(pos>>32)+1]<<parent->parent->instancet1_i.GAIN,(((uint32_t)pos)>>1),r);
                                                                                ^~~~~~
make: *** [/Users/nicotep/Library/Akso/build/xpatch.o] Error 1
shell task failed, exit value: 2
axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.ShellTask.run(ShellTask.java:120)
	at axoloti.shell.ShellTask.lambda$getJob$0(ShellTask.java:37)
	at axoloti.shell.CompilePatch.lambda$run$0(CompilePatch.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)

Compiling patch failed.
axoloti.shell.ExecutionFailedException
axoloti.shell.ExecutionFailedException
	at axoloti.shell.CompilePatch.run(CompilePatch.java:75)
	at axoloti.live.patch.PatchViewLive.lambda$goLive$7(PatchViewLive.java:275)
	at axoloti.job.JobProcessor.lambda$exec$0(JobProcessor.java:21)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by nicotep** [comment]
Forgot to give precisions : mac os 10.12.6
